package com.lbb.model;

public enum NameForApi {

    TEST_HOSTS_URL,
    ONLINE_HOSTS_URL,

    WRITE_YUQI_URL,
    WRITE_SHEBEI_URL,
    WRITE_ZHIMA_URL,
    WRITE_BACKLIST_URL,

    READ_YUQI_URL,
    READ_SHEBEI_URL,
    READ_ZHIMA_URL,
    READ_BACKLIST_URL,


    NEW_WRITE_BACKLIST,
    NEW_OWAPI_ORIGINAL_PUSH,
    NEW_OWAPI_ORIGINAL_PUSH_BLACKLIST,
    NEW_ORAPI_CREDIT_BLACKLIST,

}
